### ISSUE TITLE
Firefox doesn't show the video at the right size

### ISSUE THREAD

**Issue by thibaultmol** [FOSDEM/website#244]
Both firefox desktop (linux) and Firefox on Android show the video is a waaaaay to big video container
![Screenshot 2024-02-08 at 16-27-01 FOSDEM 2024 - FOSDEM infrastructure review](https://github.com/FOSDEM/website/assets/1010226/3d955556-c0ea-465d-aee0-b92578723a52)

**Comment by tweska** [comment]
It looks fine on Firefox 121.0.1

**Comment by thibaultmol** [comment]
Weird, it's working now yeah. Maybe some other commit fixed it.
